#!/usr/bin/env python3

import os
import subprocess

try:
    import psycopg2  # noqa
except ImportError:
    subprocess.check_call(["apt-get", "update"])
    subprocess.check_call(
        ["apt-get", "--assume-yes", "--option=Dpkg::Options::=--force-confold", "install", "python3-psycopg2",]
    )

os.environ["PYTHONPATH"] = "lib:venv"
os.execl("./src/charm.py", "./src/charm.py")
